debug: false
record_serve_info: false
skip-first-sync: false
exit-when-disconnected: false
log-slots: 7
byoc: false
noopen: false
no_heavy_check: false
trusted-x-forwarded-for: false
public_host: example.com
public_port: 8080
port: 4000
cluster_id: ${CLUSTER_ID}
cluster_secret: ${CLUSTER_SECRET}
sync_interval: 10
keepalive_timeout: 10
download_max_conn: 64
serve_limit:
    enable: false
    max_conn: 0
    upload_rate: 0
dashboard:
    enable: true
    pwa-name: GoOpenBmclApi Dashboard
    pwa-short_name: GOBA Dash
    pwa-description: Go-Openbmclapi Internal Dashboard
storages:
    - type: local
      weight: 100
      data:
        cache-path: ""
        compressor: ""
