record-serve-info: true
log-slots: 7
byoc: false
trusted-x-forwarded-for: false
public-host: ""
public-port: 0
port: 4000
cluster-id: ${CLUSTER_ID}
cluster-secret: ${CLUSTER_SECRET}
sync-interval: 10
download-max-conn: 16
cache:
  type: inmem
serve-limit:
  enable: false
  max-conn: 16384
  upload-rate: 10240
dashboard:
  enable: true
  pwa-name: GoOpenBmclApi Dashboard
  pwa-short_name: GOBA Dash
  pwa-description: Go-Openbmclapi Internal Dashboard
storages:
  - type: local
    id: local-storage-0
    weight: 100
    data:
      cache-path: cache
      compressor: ""
webdav-users:
  example-user:
    endpoint: https://webdav.example.com/path/to/endpoint/
    username: example-username
    password: example-password
advanced:
  debug-log: false
  skip-first-sync: true
  exit-when-disconnected: true
  noopen: false
  no-heavy-check: false
  keepalive-timeout: 10
