debug: false
record-serve-info: false
skip-first-sync: false
exit-when-disconnected: false
log-slots: 7
byoc: false
noopen: false
no-heavy-check: false
trusted-x-forwarded-for: false
public-host: example.com
public-port: 8080
port: 4000
cluster-id: ${CLUSTER_ID}
cluster-secret: ${CLUSTER_SECRET}
sync-interval: 10
keepalive-timeout: 10
download-max-conn: 64
serve-limit:
    enable: false
    max-conn: 123
    upload-rate: 12345
dashboard:
    enable: true
    pwa-name: GoOpenBmclApi Dashboard
    pwa-short_name: GOBA Dash
    pwa-description: Go-Openbmclapi Internal Dashboard
storages:
    - type: local
      weight: 100
      data:
        cache-path: cache
        compressor: ""
    - type: mount
      weight: 0
      data:
        path: oss_mirror
        redirect-base: https://oss.example.com/base/paths
        pre-gen-measures: false

