
name: Create tagged release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
      -
        name: Generate
        run: go generate .
      -
        name: Test
        run: go test -v ./...

  create_release:
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      -
        name: Output TAG
        id: tag
        run: |
          export RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          echo "tag=${RELEASE_VERSION}"
          echo "tag=${RELEASE_VERSION}" >> "$GITHUB_OUTPUT"
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

  build:
    runs-on: ubuntu-latest
    needs:
      - create_release
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
      -
        name: Generate
        run: go generate .
      -
        name: Build
        env:
          TAG: ${{ needs.create_release.outputs.tag }}
        run: bash ./scripts/build.sh
      -
        name: Upload Release Assets
        uses: zyxkad/upload-release-asset-dir@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_dir: ./output

  build-windows:
    runs-on: windows-2022
    needs:
      - create_release
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
      -
        name: Generate
        run: go generate .
      -
        name: Build
        env:
          TAG: ${{ needs.create_release.outputs.tag }}
          CODE_SIGN_PFX: ${{ secrets.CODE_SIGN_PFX }}
          CODE_SIGN_PFX_PASSWORD: ${{ secrets.CODE_SIGN_PFX_PASSWORD }}
        run: go run ./scripts/build-windows.go
      -
        name: Upload Release Assets
        uses: zyxkad/upload-release-asset-dir@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_dir: ./output
